"""
Every CueSeek icon asset, generated from one geometry.

    python docs/brand/icon.py

Run it after changing anything below, and never edit the generated files by hand: the phone,
the watch and the docs each carry a copy of the mark, and the only thing keeping them identical
is that they all come from here.

The mark -- "Swell" -- is a 270-degree dial open at the bottom. The active arc swells from a
hairline at 7:30 into a round handle at 1:30; after a gap, a tail tapers back to a hairline at
4:30. Tapers are filled outlines, not strokes: a stroke has one width, and the whole point of
the mark is that its width changes continuously. The reasoning is in DESIGN.md, "Identity".
"""
import math
import os

REPO = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

# ---------------------------------------------------------------------------- geometry
# On the 108 x 108 adaptive-icon canvas: 72dp visible, 66dp guaranteed. Every point below lies
# within r33 of the canvas centre. The dial's own centre is nudged to (55, 57.5) because an arc
# open at the bottom with a handle at top-right carries its weight up and right; this makes it
# look centred rather than measure centred.
CX, CY, R = 55.0, 57.5, 24.0
HANDLE_DEG, HANDLE_R = 315.0, 7.5          # 1:30
START_DEG, END_DEG = 135.0, 405.0          # 7:30 round to 4:30
HAIRLINE, FULL = 1.6, 7.0                  # width at the thin ends and at the handle


def smoothstep(t):
    """Eases at both ends, so the swell has no visible kink where it starts to thicken."""
    return t * t * (3 - 2 * t)


def at(theta, r):
    a = math.radians(theta)
    return CX + r * math.cos(a), CY + r * math.sin(a)


def taper(t0, t1, w0, w1, n):
    """Closed outline of an arc whose width eases from w0 to w1, with round caps."""
    outer, inner = [], []
    for i in range(n + 1):
        t = i / n
        th = t0 + (t1 - t0) * t
        w = w0 + (w1 - w0) * smoothstep(t)
        outer.append(at(th, R + w / 2))
        inner.append(at(th, R - w / 2))
    f = lambda p: f"{p[0]:.2f} {p[1]:.2f}"
    d = f"M {f(outer[0])} " + " ".join(f"L {f(p)}" for p in outer[1:])
    d += f" A {w1 / 2:.2f} {w1 / 2:.2f} 0 0 1 {f(inner[-1])} "
    d += " ".join(f"L {f(p)}" for p in reversed(inner[:-1]))
    d += f" A {w0 / 2:.2f} {w0 / 2:.2f} 0 0 1 {f(outer[0])} Z"
    return d


# Gaps either side of the handle: handle radius + 2.5 clearance + the 3.5 cap of a 7-wide end.
GAP = math.degrees(2 * math.asin((HANDLE_R + 2.5 + FULL / 2) / (2 * R)))
hx, hy = at(HANDLE_DEG, R)
SWELL = taper(START_DEG, HANDLE_DEG - GAP, HAIRLINE, FULL, 72)
TAIL = taper(HANDLE_DEG + GAP, END_DEG, FULL, HAIRLINE, 32)
HANDLE = (f"M {hx - HANDLE_R:.2f} {hy:.2f} A {HANDLE_R} {HANDLE_R} 0 1 0 {hx + HANDLE_R:.2f} {hy:.2f} "
          f"A {HANDLE_R} {HANDLE_R} 0 1 0 {hx - HANDLE_R:.2f} {hy:.2f} Z")
MARK = f"{SWELL} {TAIL} {HANDLE}"

# ---------------------------------------------------------------------------- colour
# All from DESIGN.md's dark scheme. One hue; the grade is lightness only.
TILE = "#FF344E38"      # primaryContainer
BRIGHT = "#FFCDE8CF"    # onPrimaryContainer -- the handle, and the swell's thick end
QUIET = "#FF79937C"     # onPrimaryContainer at ~45% over the tile -- both hairline ends


def lerp(a, b, t):
    ca = [int(a[i:i + 2], 16) for i in (3, 5, 7)]
    cb = [int(b[i:i + 2], 16) for i in (3, 5, 7)]
    return "#FF" + "".join(f"{round(x + (y - x) * t):02X}" for x, y in zip(ca, cb))


# Android's sweep gradient starts at 3 o'clock and runs clockwise -- the same convention as the
# geometry -- so an offset is just angle / 360. The tail crosses 0 degrees part-way along, so the
# colour at the seam is interpolated rather than assumed.
tail_start = HANDLE_DEG + GAP
EDGE = lerp(BRIGHT, QUIET, (360 - tail_start) / (END_DEG - tail_start))
STOPS = [
    (0.0, EDGE),
    ((END_DEG - 360) / 360, QUIET),            # tail ends
    (START_DEG / 360, QUIET),                  # swell begins
    ((HANDLE_DEG - GAP) / 360, BRIGHT),        # swell reaches the handle
    (tail_start / 360, BRIGHT),                # tail begins
    (1.0, EDGE),
]

# ---------------------------------------------------------------------------- output
HEADER = ('<?xml version="1.0" encoding="utf-8"?>\n'
          "<!-- GENERATED by docs/brand/icon.py. Do not edit by hand; see DESIGN.md, \"Identity\". -->\n")
VECTOR = ('<vector xmlns:android="http://schemas.android.com/apk/res/android"{extra}\n'
          '    android:width="108dp"\n    android:height="108dp"\n'
          '    android:viewportWidth="108"\n    android:viewportHeight="108">\n')


def graded(note):
    items = "\n".join(f'                <item android:offset="{o:.3f}" android:color="{c}" />' for o, c in STOPS)
    return (HEADER + f"<!-- {note} -->\n"
            + VECTOR.format(extra='\n    xmlns:aapt="http://schemas.android.com/aapt"')
            + f'    <path android:pathData="{MARK}">\n'
            + '        <aapt:attr name="android:fillColor">\n'
            + f'            <gradient\n                android:type="sweep"\n'
            + f'                android:centerX="{CX:g}"\n                android:centerY="{CY:g}">\n'
            + items + "\n            </gradient>\n        </aapt:attr>\n    </path>\n</vector>\n")


def flat(colour, note, background=None):
    bg = (f'    <path\n        android:fillColor="{background}"\n'
          f'        android:pathData="M0,0h108v108h-108z" />\n') if background else ""
    return (HEADER + f"<!-- {note} -->\n" + VECTOR.format(extra="") + bg
            + f'    <path\n        android:fillColor="{colour}"\n        android:pathData="{MARK}" />\n</vector>\n')


def solid(colour, note):
    return (HEADER + f"<!-- {note} -->\n" + VECTOR.format(extra="")
            + f'    <path\n        android:fillColor="{colour}"\n        android:pathData="M0,0h108v108h-108z" />\n</vector>\n')


GRADED = "The mark, graded (T3): brightest at the handle, a quieter tone of the same colour at both hairline ends."
MONO = ("Flat (T1) for Android 13+ themed icons. The system uses this as a mask and tints it, "
        "so the colour here is irrelevant; only the shape survives.")
PHONE, WEAR = "clients/android/app/src/main/res", "clients/wear/app/src/main/res"

FILES = {
    f"{PHONE}/drawable/ic_launcher_foreground.xml": graded(GRADED),
    f"{PHONE}/drawable/ic_launcher_monochrome.xml": flat("#FFFFFFFF", MONO),
    f"{PHONE}/drawable/ic_launcher_background.xml": solid(
        TILE, "The tile, primaryContainer. Chosen over near-black #0E1210, which disappears on dark wallpapers."),
    f"{WEAR}/drawable/ic_launcher_foreground.xml": graded(GRADED),
    f"{WEAR}/drawable/ic_launcher_monochrome.xml": flat("#FFFFFFFF", MONO),
    f"{WEAR}/drawable/ic_complication.xml": flat(
        BRIGHT, "Flat mark for the complication picker: small, and on somebody else's watch face, so no grade and no tile."),
    f"{WEAR}/drawable/tile_preview.xml": flat(
        BRIGHT, "The tile picker's preview: the flat mark on the black a tile is drawn on. "
                "Not a screenshot of a reading; a preview is chosen before anything has been measured.",
        background="#FF000000"),
}

# SVG masters for the website and anything else that is not Android. Flat only: SVG has no
# sweep gradient, and an approximation would be a second, slightly different mark. The graded
# form lives in the Android drawables; M6 can reproduce it with a CSS conic-gradient.
def svg(note, body, view="18 18 72 72"):
    nl = "\n"
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view}" role="img" aria-label="CueSeek">{nl}'
            f"  <!-- GENERATED by docs/brand/icon.py. {note} -->{nl}{body}</svg>{nl}")


FILES["docs/brand/cueseek-mark.svg"] = svg(
    "The mark alone, in currentColor, so it takes the colour of whatever it sits in.",
    f'  <path fill="currentColor" d="{MARK}"/>\n', view="24 26 60 56")
FILES["docs/brand/cueseek-icon.svg"] = svg(
    "The icon as it appears in a launcher: the flat mark on the primaryContainer tile.",
    f'  <rect x="18" y="18" width="72" height="72" rx="17" fill="#{TILE[3:]}"/>\n'
    f'  <path fill="#{BRIGHT[3:]}" d="{MARK}"/>\n')

if __name__ == "__main__":
    print(f"gap either side of the handle: {GAP:.2f} deg; seam colour {EDGE}")
    for rel, body in FILES.items():
        # XML forbids "--" inside a comment, and aapt fails the whole build on it. Checked
        # here because a note written in prose will reach for a dash sooner or later.
        for comment in body.split("<!--")[1:]:
            assert "--" not in comment.split("-->")[0], f"'--' inside an XML comment in {rel}"
        with open(os.path.join(REPO, rel), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(body)
        print(f"{len(body):6d}  {rel}")
