/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param actionId 
 * @param serviceId 
 * @param action 
 * @param status 
 * @param at 
 * @param error Present when `status` is `failed`.
 */
@Serializable

data class ActionProgress (

    @SerialName(value = "action_id")
    val actionId: kotlin.String,

    @SerialName(value = "service_id")
    val serviceId: kotlin.String,

    @SerialName(value = "action")
    val action: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "at")
    val at: kotlin.String,

    /* Present when `status` is `failed`. */
    @SerialName(value = "error")
    val error: kotlin.String? = null

) {


}

