/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * How much care an action warrants. Clients gate on this without knowing what the action does — which is what lets a new action ship to an existing client with a confirmation prompt already attached. 
 *
 * Values: safe,disruptive,destructive
 */
@Serializable
enum class ActionRisk(val value: kotlin.String) {

    @SerialName(value = "safe")
    safe("safe"),

    @SerialName(value = "disruptive")
    disruptive("disruptive"),

    @SerialName(value = "destructive")
    destructive("destructive");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ActionRisk) "$data" else null

        /**
         * Returns a valid [ActionRisk] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ActionRisk? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

