/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * Values: pending,running,succeeded,failed
 */
@Serializable
enum class ActionStatus(val value: kotlin.String) {

    @SerialName(value = "pending")
    pending("pending"),

    @SerialName(value = "running")
    running("running"),

    @SerialName(value = "succeeded")
    succeeded("succeeded"),

    @SerialName(value = "failed")
    failed("failed");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ActionStatus) "$data" else null

        /**
         * Returns a valid [ActionStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ActionStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

