/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * An action descriptor. Actions are DATA, not enum cases — hardcoding an action list in a client discards capability discovery entirely (ADR-0005). 
 *
 * @param id 
 * @param label 
 * @param risk 
 * @param description Optional longer explanation, shown in a confirmation dialog.
 */
@Serializable

data class Action (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "label")
    val label: kotlin.String,

    @SerialName(value = "risk")
    val risk: kotlin.String,

    /* Optional longer explanation, shown in a confirmation dialog. */
    @SerialName(value = "description")
    val description: kotlin.String? = null

) {


}

