/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param actionId Correlates this invocation with `action_progress` stream events.
 * @param serviceId 
 * @param action 
 * @param status 
 * @param acceptedAt 
 */
@Serializable

data class ActionAccepted (

    /* Correlates this invocation with `action_progress` stream events. */
    @SerialName(value = "action_id")
    val actionId: kotlin.String,

    @SerialName(value = "service_id")
    val serviceId: kotlin.String,

    @SerialName(value = "action")
    val action: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "accepted_at")
    val acceptedAt: kotlin.String

) {


}

