/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Processor load. No field is required.
 *
 * @param usagePercent Busy time as a percentage over the interval since the previous collection, across all cores.  **Absent on the first collection after the agent starts**, and that is not a defect. The kernel reports cumulative counters, so utilisation only exists as a difference between two samples; with one sample there is no answer, and zero would be a lie about an idle machine. 
 * @param cores Logical cores, for reading `load1` against.
 * @param load1 One-minute load average. Reported alongside `usage_percent` rather than instead of it: load counts processes waiting on disk as well as on CPU, so a machine can be at 4% usage and still be unusable, and only the pair says so. 
 * @param load5 
 * @param load15 
 */
@Serializable

data class CpuMetrics (

    /* Busy time as a percentage over the interval since the previous collection, across all cores.  **Absent on the first collection after the agent starts**, and that is not a defect. The kernel reports cumulative counters, so utilisation only exists as a difference between two samples; with one sample there is no answer, and zero would be a lie about an idle machine.  */
    @SerialName(value = "usage_percent")
    val usagePercent: kotlin.Float? = null,

    /* Logical cores, for reading `load1` against. */
    @SerialName(value = "cores")
    val cores: kotlin.Int? = null,

    /* One-minute load average. Reported alongside `usage_percent` rather than instead of it: load counts processes waiting on disk as well as on CPU, so a machine can be at 4% usage and still be unusable, and only the pair says so.  */
    @SerialName(value = "load1")
    val load1: kotlin.Float? = null,

    @SerialName(value = "load5")
    val load5: kotlin.Float? = null,

    @SerialName(value = "load15")
    val load15: kotlin.Float? = null

) {


}

