/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param platform 
 * @param scopes 
 * @param createdAt 
 * @param lastSeenAt Absent if the device has not made a request since pairing.
 */
@Serializable

data class Device (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "platform")
    val platform: kotlin.String,

    @SerialName(value = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    /* Absent if the device has not made a request since pairing. */
    @SerialName(value = "last_seen_at")
    val lastSeenAt: kotlin.String? = null

) {


}

