/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire

import dev.cueseek.core.api.wire.HealthReason

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status 
 * @param reachable Whether the agent could reach the service at `observed_at`.  Deliberately separate from `status` and from `reported_status`. \"We could not reach qBittorrent\" and \"qBittorrent reports itself degraded\" are different facts, and a console that conflates them lies to its operator (ADR-0005). 
 * @param reasons 
 * @param observedAt When this state was actually observed — not when it was served. Clients render staleness from this rather than presenting cached data as current. 
 * @param reportedStatus What the service says about itself, verbatim and unmapped. Absent when the service was unreachable or reports nothing. 
 */
@Serializable

data class Health (

    @SerialName(value = "status")
    val status: kotlin.String,

    /* Whether the agent could reach the service at `observed_at`.  Deliberately separate from `status` and from `reported_status`. \"We could not reach qBittorrent\" and \"qBittorrent reports itself degraded\" are different facts, and a console that conflates them lies to its operator (ADR-0005).  */
    @SerialName(value = "reachable")
    val reachable: kotlin.Boolean,

    @SerialName(value = "reasons")
    val reasons: kotlin.collections.List<HealthReason>,

    /* When this state was actually observed — not when it was served. Clients render staleness from this rather than presenting cached data as current.  */
    @SerialName(value = "observed_at")
    val observedAt: kotlin.String,

    /* What the service says about itself, verbatim and unmapped. Absent when the service was unreachable or reports nothing.  */
    @SerialName(value = "reported_status")
    val reportedStatus: kotlin.String? = null

) {


}

