/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A closed set, shared by the API, both clients and the design system's status language. Adding a fifth value is a contract change, not an implementation detail (ADR-0008, ADR-0010).  `unknown` is a real state, not an error: before the first poll completes, and whenever cached state has aged past tolerance, the honest answer is \"I don't know\". Showing stale green while the agent cannot reach a service is worse than showing nothing, because it is confidently wrong. 
 *
 * Values: healthy,degraded,unreachable,unknown
 */
@Serializable
enum class HealthStatus(val value: kotlin.String) {

    @SerialName(value = "healthy")
    healthy("healthy"),

    @SerialName(value = "degraded")
    degraded("degraded"),

    @SerialName(value = "unreachable")
    unreachable("unreachable"),

    @SerialName(value = "unknown")
    unknown("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is HealthStatus) "$data" else null

        /**
         * Returns a valid [HealthStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): HealthStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

