/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Why a service is in its current state. \"Degraded\" alone is not actionable; \"degraded: unreachable for 4m\" is, and it is also what a notification would say. 
 *
 * @param code Stable machine-readable identifier, safe to branch on.
 * @param message Human-readable explanation.
 */
@Serializable

data class HealthReason (

    /* Stable machine-readable identifier, safe to branch on. */
    @SerialName(value = "code")
    val code: kotlin.String,

    /* Human-readable explanation. */
    @SerialName(value = "message")
    val message: kotlin.String

) {


}

