/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Acknowledgement of a power action. Deliberately not [ActionAccepted], which requires `service_id` — a machine is not one of its own services, and a sentinel value there would be a small lie told on every power action forever. 
 *
 * @param actionId Correlates with a `host_action_progress` event, if one arrives.
 * @param action 
 * @param status 
 * @param acceptedAt 
 */
@Serializable

data class HostActionAccepted (

    /* Correlates with a `host_action_progress` event, if one arrives. */
    @SerialName(value = "action_id")
    val actionId: kotlin.String,

    @SerialName(value = "action")
    val action: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "accepted_at")
    val acceptedAt: kotlin.String

) {


}

