/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The outcome of a power action, which in practice means **the failure** of one: a successful reboot takes the stream with it, so the only progress that can be delivered is news that the machine is still here.  A separate schema and a separate event type rather than a widened [ActionProgress]. Relaxing that one's required `service_id` would have been smaller in the specification and much worse on a phone — a client built before this shipped would fail to parse a field it was told was mandatory, and it would fail while some *other* device pressed the button. An unknown event type is ignored safely; a malformed known one is not. 
 *
 * @param actionId 
 * @param action 
 * @param status 
 * @param at 
 * @param error Present when `status` is `failed`.
 */
@Serializable

data class HostActionProgress (

    @SerialName(value = "action_id")
    val actionId: kotlin.String,

    @SerialName(value = "action")
    val action: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "at")
    val at: kotlin.String,

    /* Present when `status` is `failed`. */
    @SerialName(value = "error")
    val error: kotlin.String? = null

) {


}

