/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Physical memory and swap. No field is required.  `available_bytes` is the number that matters and is not `total - used`: the kernel's estimate accounts for reclaimable cache, and reporting cache as consumed is the classic way to make a healthy Linux box look like it is out of memory. 
 *
 * @param totalBytes 
 * @param availableBytes What a new process could actually get, per the kernel's estimate.
 * @param usedBytes Total minus available. Present only when both of those are.
 * @param swapTotalBytes 
 * @param swapUsedBytes 
 */
@Serializable

data class MemoryMetrics (

    @SerialName(value = "total_bytes")
    val totalBytes: kotlin.Long? = null,

    /* What a new process could actually get, per the kernel's estimate. */
    @SerialName(value = "available_bytes")
    val availableBytes: kotlin.Long? = null,

    /* Total minus available. Present only when both of those are. */
    @SerialName(value = "used_bytes")
    val usedBytes: kotlin.Long? = null,

    @SerialName(value = "swap_total_bytes")
    val swapTotalBytes: kotlin.Long? = null,

    @SerialName(value = "swap_used_bytes")
    val swapUsedBytes: kotlin.Long? = null

) {


}

