/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire

import dev.cueseek.core.api.wire.PlaybackSession

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Active playback sessions on a media server.  `transcoding` is broken out because it is the operationally significant fact on a self-hosted box: direct play costs almost nothing, and one 4K transcode can saturate the CPU everything else on the host shares. A console showing only a session count would hide the number that explains a hot machine. 
 *
 * @param sessions Total active sessions. Authoritative, unlike the length of `items`.
 * @param transcoding How many of those sessions the server is transcoding.
 * @param items A bounded sample. May be shorter than `sessions`, and is empty when nothing is playing. 
 */
@Serializable

data class NowPlaying (

    /* Total active sessions. Authoritative, unlike the length of `items`. */
    @SerialName(value = "sessions")
    val sessions: kotlin.Int,

    /* How many of those sessions the server is transcoding. */
    @SerialName(value = "transcoding")
    val transcoding: kotlin.Int,

    /* A bounded sample. May be shorter than `sessions`, and is empty when nothing is playing.  */
    @SerialName(value = "items")
    val items: kotlin.collections.List<PlaybackSession>

) {


}

