/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire

import dev.cueseek.core.api.wire.Device

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param token The bearer token. Returned once and never recoverable — the agent stores only its hash. Clients must persist it in platform-secure storage. 
 * @param device 
 */
@Serializable

data class PairResponse (

    /* The bearer token. Returned once and never recoverable — the agent stores only its hash. Clients must persist it in platform-secure storage.  */
    @SerialName(value = "token")
    val token: kotlin.String,

    @SerialName(value = "device")
    val device: Device

) {


}

