/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param code The single-use pairing code displayed by the agent.
 * @param deviceName Human-readable name shown in the device list.
 * @param platform 
 */
@Serializable

data class PairRequest (

    /* The single-use pairing code displayed by the agent. */
    @SerialName(value = "code")
    val code: kotlin.String,

    /* Human-readable name shown in the device list. */
    @SerialName(value = "device_name")
    val deviceName: kotlin.String,

    @SerialName(value = "platform")
    val platform: kotlin.String

) {


}

