/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Client platform, recorded for display in the device list.
 *
 * Values: android,wearos,ios,web,desktop,cli,unknown
 */
@Serializable
enum class Platform(val value: kotlin.String) {

    @SerialName(value = "android")
    android("android"),

    @SerialName(value = "wearos")
    wearos("wearos"),

    @SerialName(value = "ios")
    ios("ios"),

    @SerialName(value = "web")
    web("web"),

    @SerialName(value = "desktop")
    desktop("desktop"),

    @SerialName(value = "cli")
    cli("cli"),

    @SerialName(value = "unknown")
    unknown("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Platform) "$data" else null

        /**
         * Returns a valid [Platform] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Platform? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

