/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Stable within one observation. Not durable across restarts.
 * @param title What is playing, as the server names it.
 * @param paused 
 * @param transcoding Whether the server is re-encoding this session. A boolean rather than Jellyfin's richer transcode reasons, which do not generalise. 
 * @param subtitle Context the title alone does not carry - an episode, an artist, a year. Absent when the service offers none; never synthesised by the agent. 
 * @param user Who is watching. Absent when the service does not say.
 * @param client The app or device playing it, as the server reports it.
 * @param positionSeconds Absent when the service reports no position.
 * @param durationSeconds Absent for live or unbounded content.
 */
@Serializable

data class PlaybackSession (

    /* Stable within one observation. Not durable across restarts. */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* What is playing, as the server names it. */
    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "paused")
    val paused: kotlin.Boolean,

    /* Whether the server is re-encoding this session. A boolean rather than Jellyfin's richer transcode reasons, which do not generalise.  */
    @SerialName(value = "transcoding")
    val transcoding: kotlin.Boolean,

    /* Context the title alone does not carry - an episode, an artist, a year. Absent when the service offers none; never synthesised by the agent.  */
    @SerialName(value = "subtitle")
    val subtitle: kotlin.String? = null,

    /* Who is watching. Absent when the service does not say. */
    @SerialName(value = "user")
    val user: kotlin.String? = null,

    /* The app or device playing it, as the server reports it. */
    @SerialName(value = "client")
    val client: kotlin.String? = null,

    /* Absent when the service reports no position. */
    @SerialName(value = "position_seconds")
    val positionSeconds: kotlin.Int? = null,

    /* Absent for live or unbounded content. */
    @SerialName(value = "duration_seconds")
    val durationSeconds: kotlin.Int? = null

) {


}

