/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Error payload following RFC 9457 (problem+json). One error shape across the whole API means clients write one error mapper rather than one per endpoint. 
 *
 * @param type URI reference identifying the problem type.
 * @param title Short, human-readable summary. Stable for a given type.
 * @param status HTTP status code.
 * @param detail Human-readable explanation specific to this occurrence.
 * @param instance URI reference identifying this specific occurrence.
 */
@Serializable

data class Problem (

    /* URI reference identifying the problem type. */
    @SerialName(value = "type")
    val type: kotlin.String,

    /* Short, human-readable summary. Stable for a given type. */
    @SerialName(value = "title")
    val title: kotlin.String,

    /* HTTP status code. */
    @SerialName(value = "status")
    val status: kotlin.Int,

    /* Human-readable explanation specific to this occurrence. */
    @SerialName(value = "detail")
    val detail: kotlin.String? = null,

    /* URI reference identifying this specific occurrence. */
    @SerialName(value = "instance")
    val instance: kotlin.String? = null

) {


}

