/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An independently grantable permission.
 *
 * Values: read,servicePeriodControl,devicesPeriodManage,hostPeriodPower
 */
@Serializable
enum class Scope(val value: kotlin.String) {

    @SerialName(value = "read")
    read("read"),

    @SerialName(value = "service.control")
    servicePeriodControl("service.control"),

    @SerialName(value = "devices.manage")
    devicesPeriodManage("devices.manage"),

    @SerialName(value = "host.power")
    hostPeriodPower("host.power");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Scope) "$data" else null

        /**
         * Returns a valid [Scope] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Scope? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

