/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire

import dev.cueseek.core.api.wire.Action
import dev.cueseek.core.api.wire.Capability
import dev.cueseek.core.api.wire.Health
import dev.cueseek.core.api.wire.NowPlaying
import dev.cueseek.core.api.wire.Transfers
import dev.cueseek.core.api.wire.WebUI

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Stable service identifier.
 * @param name Display name.
 * @param capabilities 
 * @param health 
 * @param actions Empty if the service does not implement the `control` capability.
 * @param webUi Absent unless the service advertises the `web_ui` capability. Same pairing as `control` and `actions`: the capability declares that something exists, the sibling field carries what a client needs to use it. 
 * @param nowPlaying Absent unless the service advertises the `now_playing` capability. Same capability-plus-sibling pairing as `control` and `web_ui`. 
 * @param transfers Absent unless the service advertises the `transfers` capability. Same capability-plus-sibling pairing as `control` and `web_ui`. 
 */
@Serializable

data class Service (

    /* Stable service identifier. */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* Display name. */
    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "capabilities")
    val capabilities: kotlin.collections.List<Capability>,

    @SerialName(value = "health")
    val health: Health,

    /* Empty if the service does not implement the `control` capability. */
    @SerialName(value = "actions")
    val actions: kotlin.collections.List<Action>,

    /* Absent unless the service advertises the `web_ui` capability. Same pairing as `control` and `actions`: the capability declares that something exists, the sibling field carries what a client needs to use it.  */
    @SerialName(value = "web_ui")
    val webUi: WebUI? = null,

    /* Absent unless the service advertises the `now_playing` capability. Same capability-plus-sibling pairing as `control` and `web_ui`.  */
    @SerialName(value = "now_playing")
    val nowPlaying: NowPlaying? = null,

    /* Absent unless the service advertises the `transfers` capability. Same capability-plus-sibling pairing as `control` and `web_ui`.  */
    @SerialName(value = "transfers")
    val transfers: Transfers? = null

) {


}

