/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire

import dev.cueseek.core.api.wire.Action
import dev.cueseek.core.api.wire.HostMetrics
import dev.cueseek.core.api.wire.Service
import dev.cueseek.core.api.wire.System

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Complete current state. Sent as the first event on every connection, which is what removes the need for a replay buffer. 
 *
 * @param system 
 * @param services 
 * @param hostMetrics The host's vitals as of the last collection. Absent on a platform where the agent cannot read them, and during the first seconds after startup before the first collection has run. 
 * @param hostActions Power actions the agent offers for the machine. Empty on a platform that cannot perform them, so a client renders nothing rather than buttons that would fail. Listed independently of the caller's scopes — see `GET /v1/host/actions`. 
 */
@Serializable

data class Snapshot (

    @SerialName(value = "system")
    val system: System,

    @SerialName(value = "services")
    val services: kotlin.collections.List<Service>,

    /* The host's vitals as of the last collection. Absent on a platform where the agent cannot read them, and during the first seconds after startup before the first collection has run.  */
    @SerialName(value = "host_metrics")
    val hostMetrics: HostMetrics? = null,

    /* Power actions the agent offers for the machine. Empty on a platform that cannot perform them, so a client renders nothing rather than buttons that would fail. Listed independently of the caller's scopes — see `GET /v1/host/actions`.  */
    @SerialName(value = "host_actions")
    val hostActions: kotlin.collections.List<Action>? = null

) {


}

