/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * One watched filesystem.
 *
 * @param mount The path the operator configured, verbatim.
 * @param totalBytes 
 * @param freeBytes Space available to an unprivileged process, which is what the operator can actually use. Deliberately not the raw free count, which includes the reserve only root may spend. 
 * @param filesystem Device or source backing this mount, when known. Display only.
 */
@Serializable

data class StorageMetrics (

    /* The path the operator configured, verbatim. */
    @SerialName(value = "mount")
    val mount: kotlin.String,

    @SerialName(value = "total_bytes")
    val totalBytes: kotlin.Long,

    /* Space available to an unprivileged process, which is what the operator can actually use. Deliberately not the raw free count, which includes the reserve only root may spend.  */
    @SerialName(value = "free_bytes")
    val freeBytes: kotlin.Long,

    /* Device or source backing this mount, when known. Display only. */
    @SerialName(value = "filesystem")
    val filesystem: kotlin.String? = null

) {


}

