/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire

import dev.cueseek.core.api.wire.ActionProgress
import dev.cueseek.core.api.wire.Service
import dev.cueseek.core.api.wire.Snapshot

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * One event. `schema_version` is versioned independently of the URL path, because client releases and agent releases drift apart — a Wear build will routinely be older than the agent it talks to. 
 *
 * @param type 
 * @param seq Monotonic per connection, starting at 0 for the snapshot. Lets a client detect a gap. It is not a resume token — reconnecting yields a fresh snapshot and a reset sequence. 
 * @param emittedAt 
 * @param schemaVersion Version of the event payload schema.
 * @param snapshot 
 * @param service Present when `type` is `service_updated`.
 * @param actionProgress Present when `type` is `action_progress`.
 */
@Serializable

data class StreamEnvelope (

    @SerialName(value = "type")
    val type: kotlin.String,

    /* Monotonic per connection, starting at 0 for the snapshot. Lets a client detect a gap. It is not a resume token — reconnecting yields a fresh snapshot and a reset sequence.  */
    @SerialName(value = "seq")
    val seq: kotlin.Long,

    @SerialName(value = "emitted_at")
    val emittedAt: kotlin.String,

    /* Version of the event payload schema. */
    @SerialName(value = "schema_version")
    val schemaVersion: kotlin.String,

    @SerialName(value = "snapshot")
    val snapshot: Snapshot? = null,

    /* Present when `type` is `service_updated`. */
    @SerialName(value = "service")
    val service: Service? = null,

    /* Present when `type` is `action_progress`. */
    @SerialName(value = "action_progress")
    val actionProgress: ActionProgress? = null

) {


}

