/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param hostId Stable, opaque identifier for this host. Clients key their multi-host data model on it, so it must survive restarts, hostname changes and IP changes (ADR-0008). 
 * @param hostname Human-readable host name, for display only. May change.
 * @param agentVersion Version of cueseekd.
 * @param apiVersion Version of this contract that the agent implements. Lets a client report that the agent is behind, rather than silently mis-rendering. 
 * @param startedAt When the agent process started.
 */
@Serializable

data class System (

    /* Stable, opaque identifier for this host. Clients key their multi-host data model on it, so it must survive restarts, hostname changes and IP changes (ADR-0008).  */
    @SerialName(value = "host_id")
    val hostId: kotlin.String,

    /* Human-readable host name, for display only. May change. */
    @SerialName(value = "hostname")
    val hostname: kotlin.String,

    /* Version of cueseekd. */
    @SerialName(value = "agent_version")
    val agentVersion: kotlin.String,

    /* Version of this contract that the agent implements. Lets a client report that the agent is behind, rather than silently mis-rendering.  */
    @SerialName(value = "api_version")
    val apiVersion: kotlin.String,

    /* When the agent process started. */
    @SerialName(value = "started_at")
    val startedAt: kotlin.String

) {


}

