/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * One temperature sensor.
 *
 * @param label The sensor's own name, **verbatim and unmapped** — `coretemp Package id 0`, `nvme Composite`, `acpitz`. Deliberately not an enum, for the same reason a transfer's `state` is not: naming is hardware-specific, and a shared vocabulary would either drop sensors or mislabel them. 
 * @param celsius Current reading.
 * @param highCelsius The temperature the hardware itself calls high, when it reports one. Present so a client can say whether a number is bad without hard-coding a threshold for somebody else's silicon. 
 */
@Serializable

data class ThermalMetrics (

    /* The sensor's own name, **verbatim and unmapped** — `coretemp Package id 0`, `nvme Composite`, `acpitz`. Deliberately not an enum, for the same reason a transfer's `state` is not: naming is hardware-specific, and a shared vocabulary would either drop sensors or mislabel them.  */
    @SerialName(value = "label")
    val label: kotlin.String,

    /* Current reading. */
    @SerialName(value = "celsius")
    val celsius: kotlin.Float,

    /* The temperature the hardware itself calls high, when it reports one. Present so a client can say whether a number is bad without hard-coding a threshold for somebody else's silicon.  */
    @SerialName(value = "high_celsius")
    val highCelsius: kotlin.Float? = null

) {


}

