/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire

import dev.cueseek.core.api.wire.TransferItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * In-flight transfers: torrents, usenet downloads, an import queue.  Rates are bytes per second and are the service's own aggregate, never a sum over `items` - a sampled list would understate them. 
 *
 * @param active Transfers currently moving data.
 * @param total Transfers the service is tracking at all, including paused, queued, seeding and completed. Always at least `active`. 
 * @param downloadRateBytes Aggregate download rate, bytes per second.
 * @param uploadRateBytes Aggregate upload rate, bytes per second.
 * @param items A bounded sample, most active first. May be shorter than `total`, and is empty when the service is tracking nothing. 
 */
@Serializable

data class Transfers (

    /* Transfers currently moving data. */
    @SerialName(value = "active")
    val active: kotlin.Int,

    /* Transfers the service is tracking at all, including paused, queued, seeding and completed. Always at least `active`.  */
    @SerialName(value = "total")
    val total: kotlin.Int,

    /* Aggregate download rate, bytes per second. */
    @SerialName(value = "download_rate_bytes")
    val downloadRateBytes: kotlin.Long,

    /* Aggregate upload rate, bytes per second. */
    @SerialName(value = "upload_rate_bytes")
    val uploadRateBytes: kotlin.Long,

    /* A bounded sample, most active first. May be shorter than `total`, and is empty when the service is tracking nothing.  */
    @SerialName(value = "items")
    val items: kotlin.collections.List<TransferItem>

) {


}

