/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id The service's own identifier for this transfer.
 * @param name 
 * @param state The service's own state word, **verbatim and unmapped** - `downloading`, `stalledDL`, `seeding`, `queuedDL`, `pausedUP`. Deliberately not an enum: every service in this category has its own vocabulary, and flattening them into a shared one would discard the distinction between \"stalled\" and \"queued\" that tells an operator whether to care. Clients display it and must tolerate any value. 
 * @param progress Fraction complete, 0 to 1.
 * @param sizeBytes Total size. Absent when the service does not report one.
 * @param downloadRateBytes This transfer's own rate, bytes per second.
 * @param etaSeconds Absent when unknown or effectively infinite. A service reporting a placeholder like 8640000 must not have it passed through as eight years. 
 */
@Serializable

data class TransferItem (

    /* The service's own identifier for this transfer. */
    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    /* The service's own state word, **verbatim and unmapped** - `downloading`, `stalledDL`, `seeding`, `queuedDL`, `pausedUP`. Deliberately not an enum: every service in this category has its own vocabulary, and flattening them into a shared one would discard the distinction between \"stalled\" and \"queued\" that tells an operator whether to care. Clients display it and must tolerate any value.  */
    @SerialName(value = "state")
    val state: kotlin.String,

    /* Fraction complete, 0 to 1. */
    @SerialName(value = "progress")
    val progress: kotlin.Float,

    /* Total size. Absent when the service does not report one. */
    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long? = null,

    /* This transfer's own rate, bytes per second. */
    @SerialName(value = "download_rate_bytes")
    val downloadRateBytes: kotlin.Long? = null,

    /* Absent when unknown or effectively infinite. A service reporting a placeholder like 8640000 must not have it passed through as eight years.  */
    @SerialName(value = "eta_seconds")
    val etaSeconds: kotlin.Int? = null

) {


}

