/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.cueseek.core.api.wire


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Where a service's own interface lives, as parts rather than as a URL.  **The agent never sends a whole URL, and a client must never accept one.** The agent's own `base_url` for a service is a loopback address — it polls Jellyfin at 127.0.0.1 because it runs on the same host — which is meaningless to a phone. The client already holds an address that reaches the host: the one it paired with. It composes `scheme://{paired host}:{port}{path}` from that.  Two properties fall out of this. The same configuration works over a VPN and on the LAN, because the host part is whatever the client used to get here. And a compromised or buggy agent cannot redirect a client to an arbitrary origin, or hand back a `javascript:` URL, because it never supplies an origin at all. 
 *
 * @param scheme Almost always `http`: this is a service on the operator's own private network, and ADR-0001 delegates transport security to the VPN. `https` exists for deployments that terminate TLS locally. 
 * @param port The port the service's own interface listens on.
 * @param path Path to open, including the leading slash. Defaults to `/`. Exists because a service may put its interface somewhere other than the root, and because a reverse proxy on the host may mount it under a prefix. 
 */
@Serializable

data class WebUI (

    /* Almost always `http`: this is a service on the operator's own private network, and ADR-0001 delegates transport security to the VPN. `https` exists for deployments that terminate TLS locally.  */
    @SerialName(value = "scheme")
    val scheme: WebUI.Scheme,

    /* The port the service's own interface listens on. */
    @SerialName(value = "port")
    val port: kotlin.Int,

    /* Path to open, including the leading slash. Defaults to `/`. Exists because a service may put its interface somewhere other than the root, and because a reverse proxy on the host may mount it under a prefix.  */
    @SerialName(value = "path")
    val path: kotlin.String? = "/"

) {

    /**
     * Almost always `http`: this is a service on the operator's own private network, and ADR-0001 delegates transport security to the VPN. `https` exists for deployments that terminate TLS locally. 
     *
     * Values: http,https
     */
    @Serializable
    enum class Scheme(val value: kotlin.String) {
        @SerialName(value = "http") http("http"),
        @SerialName(value = "https") https("https");
    }

}

